// Code generated by sql2go. DO NOT EDIT.

package models

import (
	"time"
)



const TableNameAdmin = "admin"

// Admin Postfix Admin - Virtual Admins
type Admin struct {
	Username      string    `gorm:"column:username;type:varchar(255);primaryKey" json:"username"`
	Password      string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Created       time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified      time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
	Active        bool      `gorm:"column:active;type:tinyint(1);not null;default:1" json:"active"`
	Superadmin    bool      `gorm:"column:superadmin;type:tinyint(1);not null" json:"superadmin"`
	Phone         string    `gorm:"column:phone;type:varchar(30);not null" json:"phone"`
	EmailOther    string    `gorm:"column:email_other;type:varchar(255);not null" json:"email_other"`
	Token         string    `gorm:"column:token;type:varchar(255);not null" json:"token"`
	TokenValidity time.Time `gorm:"column:token_validity;type:datetime;not null;default:2000-01-01 00:00:00" json:"token_validity"`
	TotpSecret    *string   `gorm:"column:totp_secret;type:varchar(255)" json:"totp_secret"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}




const TableNameAlias = "alias"

// Alias Postfix Admin - Virtual Aliases
type Alias struct {
	Address  string    `gorm:"column:address;type:varchar(255);primaryKey" json:"address"`
	Goto     string    `gorm:"column:goto;type:text;not null" json:"goto"`
	Domain   string    `gorm:"column:domain;type:varchar(255);not null;index:domain,priority:1" json:"domain"`
	Created  time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
	Active   bool      `gorm:"column:active;type:tinyint(1);not null;default:1" json:"active"`
}

// TableName Alias's table name
func (*Alias) TableName() string {
	return TableNameAlias
}




const TableNameAliasDomain = "alias_domain"

// AliasDomain Postfix Admin - Domain Aliases
type AliasDomain struct {
	AliasDomain  string    `gorm:"column:alias_domain;type:varchar(255);primaryKey" json:"alias_domain"`
	TargetDomain string    `gorm:"column:target_domain;type:varchar(255);not null;index:target_domain,priority:1" json:"target_domain"`
	Created      time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified     time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
	Active       bool      `gorm:"column:active;type:tinyint(1);not null;index:active,priority:1;default:1" json:"active"`
}

// TableName AliasDomain's table name
func (*AliasDomain) TableName() string {
	return TableNameAliasDomain
}



const TableNameConfig = "config"

// Config PostfixAdmin settings
type Config struct {
	ID    int32  `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;type:varchar(20);not null;uniqueIndex:name,priority:1" json:"name"`
	Value string `gorm:"column:value;type:varchar(20);not null" json:"value"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}




const TableNameDkim = "dkim"

// Dkim Postfix Admin - OpenDKIM Key Table
type Dkim struct {
	ID          int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	DomainName  string    `gorm:"column:domain_name;type:varchar(255);not null;index:domain_name,priority:1" json:"domain_name"`
	Description *string   `gorm:"column:description;type:varchar(255);index:domain_name,priority:2" json:"description"`
	Selector    string    `gorm:"column:selector;type:varchar(63);not null;default:default" json:"selector"`
	PrivateKey  *string   `gorm:"column:private_key;type:text" json:"private_key"`
	PublicKey   *string   `gorm:"column:public_key;type:text" json:"public_key"`
	Created     time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified    time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
}

// TableName Dkim's table name
func (*Dkim) TableName() string {
	return TableNameDkim
}




const TableNameDkimSigning = "dkim_signing"

// DkimSigning Postfix Admin - OpenDKIM Signing Table
type DkimSigning struct {
	ID       int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Author   string    `gorm:"column:author;type:varchar(255);not null;index:author,priority:1" json:"author"`
	DkimID   int32     `gorm:"column:dkim_id;type:int(11);not null;index:dkim_id,priority:1" json:"dkim_id"`
	Created  time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
}

// TableName DkimSigning's table name
func (*DkimSigning) TableName() string {
	return TableNameDkimSigning
}




const TableNameDomain = "domain"

// Domain Postfix Admin - Virtual Domains
type Domain struct {
	Domain         string    `gorm:"column:domain;type:varchar(255);primaryKey" json:"domain"`
	Description    string    `gorm:"column:description;type:varchar(255);not null" json:"description"`
	Aliases        int32     `gorm:"column:aliases;type:int(10);not null" json:"aliases"`
	Mailboxes      int32     `gorm:"column:mailboxes;type:int(10);not null" json:"mailboxes"`
	Maxquota       int64     `gorm:"column:maxquota;type:bigint(20);not null" json:"maxquota"`
	Quota          int64     `gorm:"column:quota;type:bigint(20);not null" json:"quota"`
	Transport      string    `gorm:"column:transport;type:varchar(255);not null" json:"transport"`
	Backupmx       bool      `gorm:"column:backupmx;type:tinyint(1);not null" json:"backupmx"`
	Created        time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified       time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
	Active         bool      `gorm:"column:active;type:tinyint(1);not null;default:1" json:"active"`
	PasswordExpiry *int32    `gorm:"column:password_expiry;type:int(11)" json:"password_expiry"`
}

// TableName Domain's table name
func (*Domain) TableName() string {
	return TableNameDomain
}




const TableNameDomainAdmin = "domain_admins"

// DomainAdmin Postfix Admin - Domain Admins
type DomainAdmin struct {
	Username string    `gorm:"column:username;type:varchar(255);not null;index:username,priority:1" json:"username"`
	Domain   string    `gorm:"column:domain;type:varchar(255);not null" json:"domain"`
	Created  time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Active   bool      `gorm:"column:active;type:tinyint(1);not null;default:1" json:"active"`
	ID       int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
}

// TableName DomainAdmin's table name
func (*DomainAdmin) TableName() string {
	return TableNameDomainAdmin
}




const TableNameFetchmail = "fetchmail"

// Fetchmail mapped from table <fetchmail>
type Fetchmail struct {
	ID             int32     `gorm:"column:id;type:int(11) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Mailbox        string    `gorm:"column:mailbox;type:varchar(255);not null" json:"mailbox"`
	SrcServer      string    `gorm:"column:src_server;type:varchar(255);not null" json:"src_server"`
	SrcAuth        *string   `gorm:"column:src_auth;type:enum('password','kerberos_v5','kerberos','kerberos_v4','gssapi','cram-md5','otp','ntlm','msn','ssh','any')" json:"src_auth"`
	SrcUser        string    `gorm:"column:src_user;type:varchar(255);not null" json:"src_user"`
	SrcPassword    string    `gorm:"column:src_password;type:varchar(255);not null" json:"src_password"`
	SrcFolder      string    `gorm:"column:src_folder;type:varchar(255);not null" json:"src_folder"`
	PollTime       int32     `gorm:"column:poll_time;type:int(11) unsigned;not null;default:10" json:"poll_time"`
	Fetchall       bool      `gorm:"column:fetchall;type:tinyint(1) unsigned;not null" json:"fetchall"`
	Keep           bool      `gorm:"column:keep;type:tinyint(1) unsigned;not null" json:"keep"`
	Protocol       *string   `gorm:"column:protocol;type:enum('POP3','IMAP','POP2','ETRN','AUTO')" json:"protocol"`
	Usessl         bool      `gorm:"column:usessl;type:tinyint(1) unsigned;not null" json:"usessl"`
	ExtraOptions   *string   `gorm:"column:extra_options;type:text" json:"extra_options"`
	ReturnedText   *string   `gorm:"column:returned_text;type:text" json:"returned_text"`
	Mda            *string   `gorm:"column:mda;type:varchar(255)" json:"mda"`
	Date           time.Time `gorm:"column:date;type:timestamp;not null;default:2000-01-01 00:00:00" json:"date"`
	Sslcertck      bool      `gorm:"column:sslcertck;type:tinyint(1);not null" json:"sslcertck"`
	Sslcertpath    *string   `gorm:"column:sslcertpath;type:varchar(255)" json:"sslcertpath"`
	Sslfingerprint *string   `gorm:"column:sslfingerprint;type:varchar(255)" json:"sslfingerprint"`
	Domain         *string   `gorm:"column:domain;type:varchar(255)" json:"domain"`
	Active         bool      `gorm:"column:active;type:tinyint(1);not null" json:"active"`
	Created        time.Time `gorm:"column:created;type:timestamp;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified       time.Time `gorm:"column:modified;type:timestamp;not null;default:current_timestamp()" json:"modified"`
	SrcPort        int32     `gorm:"column:src_port;type:int(11);not null" json:"src_port"`
}

// TableName Fetchmail's table name
func (*Fetchmail) TableName() string {
	return TableNameFetchmail
}




const TableNameLog = "log"

// Log Postfix Admin - Log
type Log struct {
	Timestamp time.Time `gorm:"column:timestamp;type:datetime;not null;index:domain_timestamp,priority:2;index:timestamp,priority:1;default:2000-01-01 00:00:00" json:"timestamp"`
	Username  string    `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Domain    string    `gorm:"column:domain;type:varchar(255);not null;index:domain_timestamp,priority:1" json:"domain"`
	Action    string    `gorm:"column:action;type:varchar(255);not null" json:"action"`
	Data      string    `gorm:"column:data;type:text;not null" json:"data"`
	ID        int32     `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
}

// TableName Log's table name
func (*Log) TableName() string {
	return TableNameLog
}




const TableNameMailbox = "mailbox"

// Mailbox Postfix Admin - Virtual Mailboxes
type Mailbox struct {
	Username       string    `gorm:"column:username;type:varchar(255);primaryKey" json:"username"`
	Password       string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Name           string    `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Maildir        string    `gorm:"column:maildir;type:varchar(255);not null" json:"maildir"`
	Quota          int64     `gorm:"column:quota;type:bigint(20);not null" json:"quota"`
	LocalPart      string    `gorm:"column:local_part;type:varchar(255);not null" json:"local_part"`
	Domain         string    `gorm:"column:domain;type:varchar(255);not null;index:domain,priority:1" json:"domain"`
	Created        time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Modified       time.Time `gorm:"column:modified;type:datetime;not null;default:2000-01-01 00:00:00" json:"modified"`
	Active         bool      `gorm:"column:active;type:tinyint(1);not null;default:1" json:"active"`
	Phone          string    `gorm:"column:phone;type:varchar(30);not null" json:"phone"`
	EmailOther     string    `gorm:"column:email_other;type:varchar(255);not null" json:"email_other"`
	Token          string    `gorm:"column:token;type:varchar(255);not null" json:"token"`
	TokenValidity  time.Time `gorm:"column:token_validity;type:datetime;not null;default:2000-01-01 00:00:00" json:"token_validity"`
	PasswordExpiry time.Time `gorm:"column:password_expiry;type:datetime;not null;default:2000-01-01 00:00:00" json:"password_expiry"`
	TotpSecret     *string   `gorm:"column:totp_secret;type:varchar(255)" json:"totp_secret"`
	SMTPActive     bool      `gorm:"column:smtp_active;type:tinyint(1);not null;default:1" json:"smtp_active"`
}

// TableName Mailbox's table name
func (*Mailbox) TableName() string {
	return TableNameMailbox
}



const TableNameMailboxAppPassword = "mailbox_app_password"

// MailboxAppPassword mapped from table <mailbox_app_password>
type MailboxAppPassword struct {
	ID           int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	Username     *string `gorm:"column:username;type:varchar(255)" json:"username"`
	Description  *string `gorm:"column:description;type:varchar(255)" json:"description"`
	PasswordHash *string `gorm:"column:password_hash;type:varchar(255)" json:"password_hash"`
}

// TableName MailboxAppPassword's table name
func (*MailboxAppPassword) TableName() string {
	return TableNameMailboxAppPassword
}



const TableNameQuotum = "quota"

// Quotum mapped from table <quota>
type Quotum struct {
	Username string `gorm:"column:username;type:varchar(255);primaryKey" json:"username"`
	Path     string `gorm:"column:path;type:varchar(100);primaryKey" json:"path"`
	Current  int64  `gorm:"column:current;type:bigint(20);not null" json:"current"`
}

// TableName Quotum's table name
func (*Quotum) TableName() string {
	return TableNameQuotum
}



const TableNameQuota2 = "quota2"

// Quota2 mapped from table <quota2>
type Quota2 struct {
	Username string `gorm:"column:username;type:varchar(100);primaryKey" json:"username"`
	Bytes    int64  `gorm:"column:bytes;type:bigint(20);not null" json:"bytes"`
	Messages int32  `gorm:"column:messages;type:int(11);not null" json:"messages"`
}

// TableName Quota2's table name
func (*Quota2) TableName() string {
	return TableNameQuota2
}



const TableNameTotpExceptionAddress = "totp_exception_address"

// TotpExceptionAddress mapped from table <totp_exception_address>
type TotpExceptionAddress struct {
	ID          int32   `gorm:"column:id;type:int(11);primaryKey;autoIncrement:true" json:"id"`
	IP          string  `gorm:"column:ip;type:varchar(46);not null;uniqueIndex:ip_user,priority:1" json:"ip"`
	Username    *string `gorm:"column:username;type:varchar(255);uniqueIndex:ip_user,priority:2" json:"username"`
	Description *string `gorm:"column:description;type:varchar(255)" json:"description"`
}

// TableName TotpExceptionAddress's table name
func (*TotpExceptionAddress) TableName() string {
	return TableNameTotpExceptionAddress
}




const TableNameVacation = "vacation"

// Vacation Postfix Admin - Virtual Vacation
type Vacation struct {
	Email        string    `gorm:"column:email;type:varchar(255);primaryKey;index:email,priority:1" json:"email"`
	Subject      string    `gorm:"column:subject;type:varchar(255);not null" json:"subject"`
	Body         string    `gorm:"column:body;type:text;not null" json:"body"`
	Cache        string    `gorm:"column:cache;type:text;not null" json:"cache"`
	Domain       string    `gorm:"column:domain;type:varchar(255);not null" json:"domain"`
	Created      time.Time `gorm:"column:created;type:datetime;not null;default:2000-01-01 00:00:00" json:"created"`
	Active       bool      `gorm:"column:active;type:tinyint(1);not null;default:1" json:"active"`
	Modified     time.Time `gorm:"column:modified;type:timestamp;not null;default:current_timestamp()" json:"modified"`
	Activefrom   time.Time `gorm:"column:activefrom;type:timestamp;not null;default:2000-01-01 00:00:00" json:"activefrom"`
	Activeuntil  time.Time `gorm:"column:activeuntil;type:timestamp;not null;default:2038-01-18 00:00:00" json:"activeuntil"`
	IntervalTime int32     `gorm:"column:interval_time;type:int(11);not null" json:"interval_time"`
}

// TableName Vacation's table name
func (*Vacation) TableName() string {
	return TableNameVacation
}




const TableNameVacationNotification = "vacation_notification"

// VacationNotification Postfix Admin - Virtual Vacation Notifications
type VacationNotification struct {
	OnVacation string    `gorm:"column:on_vacation;type:varchar(255);primaryKey" json:"on_vacation"`
	Notified   string    `gorm:"column:notified;type:varchar(255);primaryKey" json:"notified"`
	NotifiedAt time.Time `gorm:"column:notified_at;type:timestamp;not null;default:current_timestamp()" json:"notified_at"`
}

// TableName VacationNotification's table name
func (*VacationNotification) TableName() string {
	return TableNameVacationNotification
}

