// Code generated by sql2go. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameAdmin = "admin"

// Admin Postfix Admin - Virtual Admins
type Admin struct {
	Username      string    `gorm:"column:username;type:varchar(255);primaryKey" json:"username"`
	Password      string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Created       time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified      time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	Active        bool      `gorm:"column:active;not null;default:true" json:"active"`
	Superadmin    bool      `gorm:"column:superadmin;not null" json:"superadmin"`
	Phone         string    `gorm:"column:phone;type:varchar(30);not null" json:"phone"`
	EmailOther    string    `gorm:"column:email_other;type:varchar(255);not null" json:"email_other"`
	Token         string    `gorm:"column:token;type:varchar(255);not null" json:"token"`
	TokenValidity time.Time `gorm:"column:token_validity;not null;default:'2000-01-01 00:00:00'" json:"token_validity"`
	TOTPSecret    *string   `gorm:"column:totp_secret;type:varchar(255)" json:"totp_secret"`
}

// TableName Admin's table name
func (Admin) TableName() string {
	return TableNameAdmin
}

const TableNameAlias = "alias"

// Alias Postfix Admin - Virtual Aliases
type Alias struct {
	Address  string    `gorm:"column:address;type:varchar(255);primaryKey" json:"address"`
	Goto     string    `gorm:"column:goto;type:text;not null" json:"goto"`
	Domain   string    `gorm:"column:domain;type:varchar(255);not null;index:idx_alias_domain_idx,priority:1" json:"domain"`
	Created  time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	Active   bool      `gorm:"column:active;not null;default:true" json:"active"`
}

// TableName Alias's table name
func (Alias) TableName() string {
	return TableNameAlias
}

const TableNameAliasDomain = "alias_domain"

// AliasDomain Postfix Admin - Domain Aliases
type AliasDomain struct {
	AliasDomain  string    `gorm:"column:alias_domain;type:varchar(255);primaryKey" json:"alias_domain"`
	TargetDomain string    `gorm:"column:target_domain;type:varchar(255);not null;index:idx_alias_domain_target_domain,priority:1" json:"target_domain"`
	Created      time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified     time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	Active       bool      `gorm:"column:active;not null;index:idx_alias_domain_active,priority:1;default:true" json:"active"`
}

// TableName AliasDomain's table name
func (AliasDomain) TableName() string {
	return TableNameAliasDomain
}

const TableNameConfig = "config"

// Config PostfixAdmin settings
type Config struct {
	ID    int    `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name  string `gorm:"column:name;type:varchar(20);not null;uniqueIndex:idx_config_name,priority:1" json:"name"`
	Value string `gorm:"column:value;type:varchar(20);not null" json:"value"`
}

// TableName Config's table name
func (Config) TableName() string {
	return TableNameConfig
}

const TableNameDkim = "dkim"

// Dkim Postfix Admin - OpenDKIM Key Table
type DKIM struct {
	ID          int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DomainName  string    `gorm:"column:domain_name;type:varchar(255);not null;index:idx_dkim_domain_name,priority:1" json:"domain_name"`
	Description *string   `gorm:"column:description;type:varchar(255);index:idx_dkim_domain_name,priority:2" json:"description"`
	Selector    string    `gorm:"column:selector;type:varchar(63);not null;default:default" json:"selector"`
	PrivateKey  *string   `gorm:"column:private_key;type:text" json:"private_key"`
	PublicKey   *string   `gorm:"column:public_key;type:text" json:"public_key"`
	Created     time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified    time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	Domain      Domain    `gorm:"foreignKey:DomainName;references:Domain;constraint:OnDelete:CASCADE" json:"-"`
}

// TableName Dkim's table name
func (DKIM) TableName() string {
	return TableNameDkim
}

const TableNameDkimSigning = "dkim_signing"

// DkimSigning Postfix Admin - OpenDKIM Signing Table
type DKIMSigning struct {
	ID       int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Author   string    `gorm:"column:author;type:varchar(255);not null;index:idx_dkim_signing_author,priority:1" json:"author"`
	DKIMID   int       `gorm:"column:dkim_id;not null;index:idx_dkim_signing_dkim_id,priority:1" json:"dkim_id"`
	Created  time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	DKIM     DKIM      `gorm:"foreignKey:DKIMID;references:ID;constraint:OnDelete:CASCADE" json:"-"`
}

// TableName DkimSigning's table name
func (DKIMSigning) TableName() string {
	return TableNameDkimSigning
}

const TableNameDomain = "domain"

// Domain Postfix Admin - Virtual Domains
type Domain struct {
	Domain         string    `gorm:"column:domain;type:varchar(255);primaryKey" json:"domain"`
	Description    string    `gorm:"column:description;type:varchar(255);not null" json:"description"`
	Aliases        int       `gorm:"column:aliases;not null" json:"aliases"`
	Mailboxes      int       `gorm:"column:mailboxes;not null" json:"mailboxes"`
	MaxQuota       int64     `gorm:"column:maxquota;not null" json:"maxquota"`
	Quota          int64     `gorm:"column:quota;not null" json:"quota"`
	Transport      string    `gorm:"column:transport;type:varchar(255);not null" json:"transport"`
	BackupMX       bool      `gorm:"column:backupmx;not null" json:"backupmx"`
	Created        time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified       time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	Active         bool      `gorm:"column:active;not null;default:true" json:"active"`
	PasswordExpiry *int      `gorm:"column:password_expiry" json:"password_expiry"`
}

// TableName Domain's table name
func (Domain) TableName() string {
	return TableNameDomain
}

const TableNameDomainAdmin = "domain_admins"

// DomainAdmin Postfix Admin - Domain Admins
type DomainAdmin struct {
	Username string    `gorm:"column:username;type:varchar(255);not null;index:idx_domain_admins_username,priority:1" json:"username"`
	Domain   string    `gorm:"column:domain;type:varchar(255);not null" json:"domain"`
	Created  time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Active   bool      `gorm:"column:active;not null;default:true" json:"active"`
	ID       int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName DomainAdmin's table name
func (DomainAdmin) TableName() string {
	return TableNameDomainAdmin
}

const TableNameFetchmail = "fetchmail"

// Fetchmail mapped from table <fetchmail>
type Fetchmail struct {
	ID             uint      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Mailbox        string    `gorm:"column:mailbox;type:varchar(255);not null" json:"mailbox"`
	SrcServer      string    `gorm:"column:src_server;type:varchar(255);not null" json:"src_server"`
	SrcAuth        *string   `gorm:"column:src_auth;type:varchar(255);check:src_auth IN ('password','kerberos_v5','kerberos','kerberos_v4','gssapi','cram-md5','otp','ntlm','msn','ssh','any')" json:"src_auth"`
	SrcUser        string    `gorm:"column:src_user;type:varchar(255);not null" json:"src_user"`
	SrcPassword    string    `gorm:"column:src_password;type:varchar(255);not null" json:"src_password"`
	SrcFolder      string    `gorm:"column:src_folder;type:varchar(255);not null" json:"src_folder"`
	PollTime       uint      `gorm:"column:poll_time;not null;default:10" json:"poll_time"`
	Fetchall       bool      `gorm:"column:fetchall;not null" json:"fetchall"`
	Keep           bool      `gorm:"column:keep;not null" json:"keep"`
	Protocol       *string   `gorm:"column:protocol;type:varchar(255);check:protocol IN ('POP3','IMAP','POP2','ETRN','AUTO')" json:"protocol"`
	UseSSL         bool      `gorm:"column:usessl;not null" json:"usessl"`
	ExtraOptions   *string   `gorm:"column:extra_options;type:text" json:"extra_options"`
	ReturnedText   *string   `gorm:"column:returned_text;type:text" json:"returned_text"`
	Mda            *string   `gorm:"column:mda;type:varchar(255)" json:"mda"`
	Date           time.Time `gorm:"column:date;not null;default:'2000-01-01 00:00:00'" json:"date"`
	SSLCertCk      bool      `gorm:"column:sslcertck;not null" json:"sslcertck"`
	SSLCertPath    string    `gorm:"column:sslcertpath;type:varchar(255)" json:"sslcertpath"`
	SSLFingerprint string    `gorm:"column:sslfingerprint;type:varchar(255)" json:"sslfingerprint"`
	Domain         string    `gorm:"column:domain;type:varchar(255)" json:"domain"`
	Active         bool      `gorm:"column:active;not null" json:"active"`
	Created        time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified       time.Time `gorm:"column:modified;not null;default:CURRENT_TIMESTAMP" json:"modified"`
	SrcPort        int       `gorm:"column:src_port;not null" json:"src_port"`
}

// TableName Fetchmail's table name
func (Fetchmail) TableName() string {
	return TableNameFetchmail
}

const TableNameLog = "log"

// Log Postfix Admin - Log
type Log struct {
	Timestamp time.Time `gorm:"column:timestamp;not null;index:idx_log_domain_timestamp,priority:2;index:idx_log_timestamp,priority:1;default:'2000-01-01 00:00:00'" json:"timestamp"`
	Username  string    `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Domain    string    `gorm:"column:domain;type:varchar(255);not null;index:idx_log_domain_timestamp,priority:1" json:"domain"`
	Action    string    `gorm:"column:action;type:varchar(255);not null" json:"action"`
	Data      string    `gorm:"column:data;type:text;not null" json:"data"`
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
}

// TableName Log's table name
func (Log) TableName() string {
	return TableNameLog
}

const TableNameMailbox = "mailbox"

// Mailbox Postfix Admin - Virtual Mailboxes
type Mailbox struct {
	Username       string    `gorm:"column:username;type:varchar(255);primaryKey" json:"username"`
	Password       string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Name           string    `gorm:"column:name;type:varchar(255);not null" json:"name"`
	Maildir        string    `gorm:"column:maildir;type:varchar(255);not null" json:"maildir"`
	Quota          int64     `gorm:"column:quota;not null" json:"quota"`
	LocalPart      string    `gorm:"column:local_part;type:varchar(255);not null" json:"local_part"`
	Domain         string    `gorm:"column:domain;type:varchar(255);not null;index:idx_mailbox_domain,priority:1" json:"domain"`
	Transport      string    `gorm:"column:transport;type:varchar(255);not null;default:''" json:"transport"`
	Created        time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified       time.Time `gorm:"column:modified;not null;default:'2000-01-01 00:00:00'" json:"modified"`
	Active         bool      `gorm:"column:active;not null;default:true" json:"active"`
	Phone          string    `gorm:"column:phone;type:varchar(30);not null" json:"phone"`
	EmailOther     string    `gorm:"column:email_other;type:varchar(255);not null" json:"email_other"`
	Token          string    `gorm:"column:token;type:varchar(255);not null" json:"token"`
	TokenValidity  time.Time `gorm:"column:token_validity;not null;default:'2000-01-01 00:00:00'" json:"token_validity"`
	PasswordExpiry time.Time `gorm:"column:password_expiry;not null;default:'2000-01-01 00:00:00'" json:"password_expiry"`
	TOTPSecret     *string   `gorm:"column:totp_secret;type:varchar(255)" json:"totp_secret"`
	SMTPActive     bool      `gorm:"column:smtp_active;not null;default:true" json:"smtp_active"`
}

// TableName Mailbox's table name
func (Mailbox) TableName() string {
	return TableNameMailbox
}

const TableNameMailboxAppPassword = "mailbox_app_password"

// MailboxAppPassword mapped from table <mailbox_app_password>
type MailboxAppPassword struct {
	ID           int     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username     *string `gorm:"column:username;type:varchar(255)" json:"username"`
	Description  *string `gorm:"column:description;type:varchar(255)" json:"description"`
	PasswordHash *string `gorm:"column:password_hash;type:varchar(255)" json:"password_hash"`
}

// TableName MailboxAppPassword's table name
func (MailboxAppPassword) TableName() string {
	return TableNameMailboxAppPassword
}

const TableNameQuotum = "quota"

// Quotum mapped from table <quota>
type Quota struct {
	Username string `gorm:"column:username;type:varchar(255);primaryKey" json:"username"`
	Path     string `gorm:"column:path;type:varchar(100);primaryKey" json:"path"`
	Current  int64  `gorm:"column:current;not null" json:"current"`
}

// TableName Quotum's table name
func (Quota) TableName() string {
	return TableNameQuotum
}

const TableNameQuota2 = "quota2"

// Quota2 mapped from table <quota2>
type Quota2 struct {
	Username string `gorm:"column:username;type:varchar(100);primaryKey" json:"username"`
	Bytes    int64  `gorm:"column:bytes;not null" json:"bytes"`
	Messages int    `gorm:"column:messages;not null" json:"messages"`
}

// TableName Quota2's table name
func (Quota2) TableName() string {
	return TableNameQuota2
}

const TableNameTotpExceptionAddress = "totp_exception_address"

// TotpExceptionAddress mapped from table <totp_exception_address>
type TOTPExceptionAddress struct {
	ID          int     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IP          string  `gorm:"column:ip;type:varchar(46);not null;uniqueIndex:idx_totp_ip_user,priority:1" json:"ip"`
	Username    *string `gorm:"column:username;type:varchar(255);uniqueIndex:idx_totp_ip_user,priority:2" json:"username"`
	Description *string `gorm:"column:description;type:varchar(255)" json:"description"`
}

// TableName TotpExceptionAddress's table name
func (TOTPExceptionAddress) TableName() string {
	return TableNameTotpExceptionAddress
}

const TableNameVacation = "vacation"

// Vacation Postfix Admin - Virtual Vacation
type Vacation struct {
	Email        string    `gorm:"column:email;type:varchar(255);primaryKey;index:idx_vacation_email,priority:1" json:"email"`
	Subject      string    `gorm:"column:subject;type:varchar(255);not null" json:"subject"`
	Body         string    `gorm:"column:body;type:text;not null" json:"body"`
	Cache        string    `gorm:"column:cache;type:text;not null" json:"cache"`
	Domain       string    `gorm:"column:domain;type:varchar(255);not null" json:"domain"`
	Created      time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Active       bool      `gorm:"column:active;not null;default:true" json:"active"`
	Modified     time.Time `gorm:"column:modified;not null;default:CURRENT_TIMESTAMP" json:"modified"`
	ActiveFrom   time.Time `gorm:"column:activefrom;not null;default:'2000-01-01 00:00:00'" json:"activefrom"`
	ActiveUntil  time.Time `gorm:"column:activeuntil;not null;default:'2038-01-18 00:00:00'" json:"activeuntil"`
	IntervalTime int       `gorm:"column:interval_time;not null" json:"interval_time"`
}

// TableName Vacation's table name
func (Vacation) TableName() string {
	return TableNameVacation
}

const TableNameVacationNotification = "vacation_notification"

// VacationNotification Postfix Admin - Virtual Vacation Notifications
type VacationNotification struct {
	OnVacation string    `gorm:"column:on_vacation;type:varchar(255);primaryKey" json:"on_vacation"`
	Notified   string    `gorm:"column:notified;type:varchar(255);primaryKey" json:"notified"`
	NotifiedAt time.Time `gorm:"column:notified_at;not null;default:CURRENT_TIMESTAMP" json:"notified_at"`
	Vacation   Vacation  `gorm:"foreignKey:OnVacation;references:Email;constraint:OnDelete:CASCADE" json:"-"`
}

// TableName VacationNotification's table name
func (VacationNotification) TableName() string {
	return TableNameVacationNotification
}

const TableNameMaillog = "maillog"

// Maillog represents the 'maillog' table — stores FILTER entries from mail.log
type Maillog struct {
	LogID      int       `gorm:"column:logid;primaryKey;autoIncrement;not null" json:"logid"`
	Tstamp     int64     `gorm:"column:tstamp;not null;default:0;index" json:"tstamp"`
	LogDate    time.Time `gorm:"column:logdate;type:date;not null" json:"logdate"`
	ProcNum    int       `gorm:"column:procnum;not null;default:0" json:"procnum"`
	MFrom      string    `gorm:"column:m_from;type:varchar(150);not null;default:''" json:"m_from"`
	MTo        string    `gorm:"column:m_to;type:varchar(150);not null;default:''" json:"m_to"`
	DomainTo   string    `gorm:"column:domain_to;type:varchar(150);not null;default:''" json:"domain_to"`
	Helo       string    `gorm:"column:helo;type:varchar(150);not null;default:''" json:"helo"`
	HostIP     string    `gorm:"column:host_ip;type:varchar(150);not null;default:''" json:"host_ip"`
	HostName   string    `gorm:"column:host_name;type:varchar(150);not null;default:''" json:"host_name"`
	MsgSize    int64     `gorm:"column:msgsize;not null;default:0" json:"msgsize"`
	DomainFrom string    `gorm:"column:domain_from;type:varchar(150);not null;default:''" json:"domain_from"`
}

func (Maillog) TableName() string { return TableNameMaillog }

const TableNameTransportList = "transport_list"

// TransportList mapped from table <transport_list>
type TransportList struct {
	ID        int       `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Domain    string    `gorm:"column:domain;type:varchar(255);not null;uniqueIndex" json:"domain"`
	Transport string    `gorm:"column:transport;type:varchar(255);not null" json:"transport"`
	Created   time.Time `gorm:"column:created;not null;default:'2000-01-01 00:00:00'" json:"created"`
	Modified  time.Time `gorm:"column:modified;not null;default:CURRENT_TIMESTAMP" json:"modified"`
	Active    bool      `gorm:"column:active;not null;default:true" json:"active"`
}

// TableName TransportList's table name
func (TransportList) TableName() string {
	return TableNameTransportList
}
